---
version: 0.2
phases:
  pre_build:
      commands:
      - VERSION="$(date +%Y-%m-%d.%H.%M.%S).$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
      - printenv
      ./build.sh $LAMBDA_BUCKET
  post_build:
    commands:
      - uname -a
